### ISSUE TITLE
Today at midnight

### ISSUE THREAD

**Issue by kaspar-allenbach** [carlcs/craft-autoexpire#2]
You've seen my Ticket on [Craft StackExchange](https://craftcms.stackexchange.com/questions/12702/show-events-until-midnight/)

It works well but there is one thing I don't understand: 

I have set the expiry date to midnight of each day. In your expiry plugin I write:
`{ konzertDatum|date_modify('midnight')|date('c') }`

This sets the event of the `10 Dec. 2015 20:00` correctly to `10 Dec. 2015 00:00`
But this sets the status already to expired altough it's not midnight yet. Why is that? Is the time beeing ignored by the status function?

**Comment by carlcs** [comment]
Try "tomorrow". I think the day starts at midnight and ends at 12:59:59 pm.
http://php.net/manual/de/datetime.formats.relative.php

**Comment by kaspar-allenbach** [comment]
Relative dates are hard :(

Thanks.
