### ISSUE TITLE
No Section avalable

### ISSUE THREAD

**Issue by kaspar-allenbach** [carlcs/craft-autoexpire#3]
Hi. I can only choose Entry types but no Sections. It seems as if the first section is chosen by default (alphabetically)

![bildschirmfoto 2016-06-19 um 14 06 57](https://cloud.githubusercontent.com/assets/762213/16177675/584cb4c2-3634-11e6-8fd2-c86fcaa082c0.png)

**Comment by carlcs** [comment]
Craft Personal licenses used to allow just one section, but this changed with Craft 2.5. I updated the plugin to show the sections dropdown also for Craft Personal installations.

https://github.com/carlcs/craft-autoexpire/archive/2cc10b1.zip
