### ISSUE TITLE
Grab last date from Supertable

### ISSUE THREAD

**Issue by kaspar-allenbach** [carlcs/craft-autoexpire#4]
Hi carlcs.

I have a pretty complex event channel which has multiple dates per event. So I created a [supertable](https://github.com/engram-design/SuperTable) with the possibility for multiple dates:

![bildschirmfoto 2016-09-15 um 09 30 43](https://cloud.githubusercontent.com/assets/762213/18541691/24f6d098-7b27-11e6-896b-78d4eae119c6.png)

How can I grab the last date and pull it into the expiryDate with your plugin? The sintax is not the same in fields as within the template.

That's the template code:

```
{% for block in entry.gigDate %}
    {{ block.konzertdatum | date('d.m.Y - G:i') }}Uhr
{% endfor %}
```

In your plugin I tried something like:

```
{ for block in entry.gigDate.last() }{ block.konzertdatum |date_modify('+1 day') | date('c') }{ endfor }
```

But this isn't working.

Irgendeine Idee?

**Comment by carlcs** [comment]
Sorry for the late reply, hopefully my answer will still be helpful.

The plugin supports the same syntax for the date field as [Dynamic Entry Titles](https://craftcms.com/docs/sections-and-entries#dynamic-entry-titles), so normal Twig is just fine. But you must return one single date as a string, a for-loop would output multiple dates.

I’m not exactly sure what you’re after, but try something like this

``` Twig
{% if entry.gigDate|length %}
    {{ entry.gigDate.last().konzertdatum|date_modify('+1 day')|date('c') }}
{% endif %}
```

**Comment by kaspar-allenbach** [comment]
Thanks. The whole thing I've created was a bit complex. I had a event channel which had one or more event dates. So I created multiple dates with supertable.
